# Styles...
foreground: &foreground "#d5c4a1"
background: &background "#32302f"
current_line: &current_line "#ebdbb2"
selection: &selection "#3c3735"
comment: &comment "#bdad93"
cyan: &cyan "#8ec07c"
green: &green "#b8bb26"
orange: &orange "#d79920"
magenta: &magenta "#d3869b"
blue: &blue "#83a598"
red: &red "#fb4934"
text: &text "#32302f"

gui:
  theme:
    activeBorderColor:
      - *green
      - bold
    inactiveBorderColor:
      - *comment
    searchingActiveBorderColor:
      - *cyan
      - bold
    optionsTextColor:
      - *blue
    selectedLineBgColor:
      - *selection
    selectedRangeBgColor:
      - *blue
    cherryPickedCommitBgColor:
      - *cyan
    cherryPickedCommitFgColor:
      - *blue
    unstagedChangesColor:
      - *red
    defaultFgColor:
      - *foreground
